services:
    - docker

before_script:
    - docker build -f "Dockerfile" -t metasploit:latest .
    - docker run -it --rm -e POSTGRES_PASSWORD=mysecretpassword metasploit:latest
      
script:
     - msfconsole
     - msfdb run

after_script:
    - docker stop metasploit:latest