services:
    - docker

before_script:
    - docker build -f "Dockerfile" -t metasploit:latest .
    
script:
    - docker run -it --rm -e POSTGRES_PASSWORD=mysecretpassword metasploit:latest msfdb run

after_script:
    - docker stop metasploit:latest