services:
    - docker

before_script:
    - docker build -f "Dockerfile" -t metasploit:latest .
    
script:
    - docker run -d --rm -e POSTGRES_PASSWORD=mysecretpassword metasploit:latest service postgresql start
    - docker exec -it metasploit:latest mfsdb init

after_script:
    - docker stop metasploit:latest